### ISSUE TITLE
Specify the units for settleTime or use elm-units Duration instead

### ISSUE THREAD

**Issue by MartinSStewart** [fredcy/elm-debouncer#1]
The documentation for `init` says
```
Initialize the debouncer with the time to wait for changing values to settle and the initial settled value.
```
It doesn't say if the settle time parameter is in seconds or milliseconds. To figure that out I had to look at the source code. I think it would be best if this package used the `Duration` type from `ianmackenzie/elm-units` as then it's up to the user if they want to write `Duration.milliseconds 1000` or `Duration.seconds 1`. If you decide against that, I recommend at least mentioning the units in the `init` function's documentation.

**Comment by fredcy** [comment]
Thanks for reporting this issue. Your Duration idea is good and I also want to avoid most dependencies, so I'm going to leave it as just a comment change for now.
